name: Android Lint
run-name: Android Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  android-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: npm install-expo-modules@latest
      - name: Run Lint
        run: ./Android/gradlew lint
        continue-on-error: false